# Version of the docker compose syntax. recently version is not needed to be mentioned.
# version: "3.9"

# Docker compose consists of one more services as needed for the app.
services:
  # app is Name of our service.
  app:
    # To build the docker file in our current directory, And the context we are using for our app is root/current directory that is represented as "."
    build:
      context: .
      # Build an argument DEV set the value to True. for setting up the dev requirements. 
      args:
        - DEV=true
    # Ports maps our local 8000 to the port 8000 of the docker container. This is how we have access to connect to the server.
    ports:
      - "8000:8000"
    # Volumes are the way of mapping directories from our local system to the docker container.
    volumes:
      - ./app:/app
    # Command that is used to run the service.
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    # These are used to tell the app service how to connect to the DB. These creds should match the postgres db creds. 
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    # App service will wait until the db service is up and running.
    depends_on:
      - db

  # Defining the db service for the docker. Here db is the hostname of the service. 
  db:
    # Defining a light weight db docker image postgres:13-alpine tag. Which is available in docker website.
    image: postgres:13-alpine
    # Mapping the directory from the local machine to this container.
    # dev-db-data:                This is the named volume and this should match the volume name of the local machine.
    # /var/lib/postgresql/data    This is the path where the data is stored in the container.(to get this path check the official documentation of postgres)
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    # To set the initial DB configuration for new DB service. This for only local development service for production we have to use complex creds.
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

# This is local machine volume directory. Volumes/Named volumes are used for Persistent data, Maps directory in container to local machine. this file system is automatically handled by docker compose.
volumes:
  dev-db-data:
